grafana:
  ingress:
    ## If true, Grafana Ingress will be created
    ##
    enabled: true

    ## IngressClassName for Grafana Ingress.
    ## Should be provided if Ingress is enable.
    ##
    ingressClassName: traefik

    annotations: 
      kubernetes.io/ingress.allow-http: "false"
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.middlewares: prometheus-stripprefix@kubernetescrd
      ingress.kubernetes.io/ssl-redirect: "false"
      cert-manager.io/issuer: prod-issuer
      cert-manager.io/issuer-kind: OriginIssuer
      cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com

    ## Hostnames.
    ## Must be provided if Ingress is enable.
    ##
    # hosts:
    #   - grafana.domain.com
    hosts:
      - kube.minhviet.cc

    ## Path for grafana ingress
    path: /grafana
    pathType: Prefix

    ## TLS configuration for grafana Ingress
    ## Secret must be manually created in the namespace
    ##
    tls:
      - secretName: grafana-tls
        hosts:
          - kube.minhviet.cc
    # - secretName: grafana-general-tls
    #   hosts:
    #   - grafana.example.com

  # # To make Grafana persistent (Using Statefulset)
  # #
  # persistence:
  #   enabled: true
  #   type: sts
  #   storageClassName: "storageClassName"
  #   accessModes:
  #     - ReadWriteOnce
  #   size: 20Gi
  #   finalizers:
  #     - kubernetes.io/pvc-protection

  service:
    type: LoadBalancer
    port: 8033
    targetPort: 3000

  grafana.ini:
    server:
      root_url: /grafana

  sidecar:
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
      isDefaultDatasource: true
      timeout: 30
      defaultDatasourceScrapeInterval: 15s

  admin:
  ## Name of the secret. Can be templated.
    existingSecret: grafana-auth-secret
    userKey: admin-user
    passwordKey: admin-password

  persistence:
    enabled: true
    type: sts
    accessModes:
      - ReadWriteOnce
    size: 5Gi
    finalizers:
      - kubernetes.io/pvc-protection

prometheus:
  service:
    type: LoadBalancer

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations: 
      kubernetes.io/ingress.allow-http: "false"
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.middlewares: prometheus-stripprefix@kubernetescrd
      ingress.kubernetes.io/ssl-redirect: "false"
      cert-manager.io/issuer: prod-issuer
      cert-manager.io/issuer-kind: OriginIssuer
      cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com

    hosts:
      - kube.minhviet.cc

    paths:
      - /prometheus
    pathType: Prefix

    tls:
      - secretName: prometheus-tls
        hosts:
          - kube.minhviet.cc

  prometheusSpec:
    scrapeInterval: 15s
    scrapeTimeout: 30s
    externalUrl: /prometheus

additionalPrometheusRulesMap:
  devops-efrei:
    groups:
      - name: devops
        rules:
        # alert when there are less than 2 pods for 30s
        - alert: InsufficientDevPods
          expr: kube_deployment_status_replicas_ready{namespace="devops-dev", deployment="java-deployment"} < 2
          for: 30s
          labels:
            severity: page
          annotations:
            summary: Insufficient pods in dev
        - alert: InsufficientProdPods
          expr: kube_deployment_status_replicas_ready{namespace="devops-prod", deployment="java-deployment"} < 2
          for: 30s
          labels:
            severity: page
          annotations:
            summary: Insufficient pods in prod


alertmanager:
  service:
    type: LoadBalancer
  
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations: 
      kubernetes.io/ingress.allow-http: "false"
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.middlewares: prometheus-stripprefix@kubernetescrd
      ingress.kubernetes.io/ssl-redirect: "false"
      cert-manager.io/issuer: prod-issuer
      cert-manager.io/issuer-kind: OriginIssuer
      cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com

    hosts:
      - kube.minhviet.cc

    paths:
      - /alertmanager
    pathType: Prefix

    tls:
      - secretName: prometheus-tls
        hosts:
          - kube.minhviet.cc
